import React, { useState } from "react";
import PageHead from "../shared/PageHead.tsx";
import Panel from "../shared/Panel.tsx";
import Chip from "../shared/Chip.tsx";
import Note from "../shared/Note.tsx";
import SourceFlag from "../shared/SourceFlag.tsx";
import DecisionChip from "../shared/DecisionChip.tsx";
import aegisApi from "../../data/aegisApi.ts";
import { SESSION } from "../../data/fixtures.js";

export default function Investigations({ events, analysis, analysisSource, setAnalysis, go }: any) {
  const deny = events.find((e: any) => e.decision === "DENY");
  const targetEvent = deny || events[events.length - 1];
  const [running, setRunning] = useState(false);

  const runInvestigation = async () => {
    if (!targetEvent || !setAnalysis) return;
    setRunning(true);
    try {
      const result = await aegisApi.investigate(targetEvent.id);
      setAnalysis(result);
    } finally {
      setRunning(false);
    }
  };

  return (
    <>
      <PageHead
        title="Investigations"
        desc="Grounded forensic synthesis from recorded evidence. Amazon Bedrock is invoked post-hoc on bounded ledger events and holds zero runtime authorization authority."
        actions={
          <>
            <SourceFlag source={analysisSource || "UNAVAILABLE"} />
            <button className="btn primary" onClick={runInvestigation} disabled={!targetEvent || running}>
              {running ? "Running investigation..." : "Run post-hoc investigation"}
            </button>
            <button className="btn" onClick={() => go("tests")}>Security tests</button>
          </>
        }
      />

      <Panel flush style={{ marginBottom: "var(--s5)" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "var(--s5)", padding: "var(--s4)", flexWrap: "wrap" }}>
          <div>
            <div className="mono dim" style={{ fontSize: 9.5, letterSpacing: ".12em" }}>TRIGGERING EVENT</div>
            <div className="mono" style={{ fontSize: 13, marginTop: 2 }}>{targetEvent ? targetEvent.id : "NO_EVENT_RECORDED"}</div>
          </div>
          <div>
            <div className="mono dim" style={{ fontSize: 9.5, letterSpacing: ".12em" }}>SESSION</div>
            <div className="mono" style={{ fontSize: 13, marginTop: 2 }}>{targetEvent?.sessionId || "NO_SESSION_RECORDED"}</div>
          </div>
          <div>
            <div className="mono dim" style={{ fontSize: 9.5, letterSpacing: ".12em" }}>EVIDENCE LEDGER</div>
            <div style={{ marginTop: 2 }}>
              <span className="mono" style={{ fontSize: 13 }}>{events.length}</span>{" "}
              <span className="dim mono" style={{ fontSize: 11 }}>EVENTS</span>
            </div>
          </div>
          <div style={{ marginLeft: "auto" }}>
            <div className="mono dim" style={{ fontSize: 9.5, letterSpacing: ".12em", marginBottom: 5 }}>BEDROCK STATE</div>
            <Chip kind={(analysisSource || "UNAVAILABLE") === "LIVE_VERIFIED" ? "allow" : "info"}>
              {(analysisSource || "UNAVAILABLE").replace(/_/g, " ")}
            </Chip>
          </div>
        </div>
      </Panel>

      <Panel title="AUTHORIZATION VS POST-HOC INVESTIGATION" flush>
        <div style={{ padding: "var(--s4)", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: "var(--s3)" }}>
          {[
            ["RUNTIME REQUEST", targetEvent?.resource || "NO_EVENT_RECORDED", "agent asks for a tool operation"],
            ["CEDAR AUTHORIZATION", targetEvent?.authProvider || "LOCAL / FALLBACK", "runtime authority"],
            ["ALLOW / DENY", targetEvent?.decision || "UNKNOWN", <DecisionChip d={targetEvent?.decision} />],
            ["RECORDED EVIDENCE", targetEvent?.id || "NO_EVENT_RECORDED", "hash-chain event"],
            ["POST-HOC INVESTIGATION", analysis.generatedBy || "NOT RUN", "advisory analysis only"],
          ].map(([label, value, sub]: any) => (
            <div key={label} className="bx">
              <div className="l">{label}</div>
              <div className="n mono" style={{ wordBreak: "break-word" }}>{value}</div>
              <div className="s" style={{ marginTop: 8 }}>{sub}</div>
            </div>
          ))}
        </div>
        <div style={{ padding: "12px 16px", borderTop: "1px solid var(--line)" }}>
          <Note kind="info">
            Bedrock is post-hoc only. It analyzes recorded evidence after Cedar has already made
            the runtime decision and never participates in authorization.
          </Note>
        </div>
      </Panel>

      <div className="grid g3">
        <div style={{ gridColumn: "1 / -2" }}>
          <Panel title="WHAT HAPPENED" flush right={<span className="dim mono" style={{ fontSize: 10 }}>generated by {analysis.generatedBy}</span>}>
            <div style={{ padding: "var(--s4)", fontSize: 14, lineHeight: 1.6 }}>
              {analysis.whatHappened.map((p: any, i: any) => (
                <p key={i} style={{ marginTop: i === 0 ? 0 : "1em", marginBottom: 0 }}>{p}</p>
              ))}
            </div>
          </Panel>

          <Panel title="BASIS OF ANALYSIS" flush>
            <div style={{ padding: "var(--s4)" }}>
              {analysis.basis.map((b: any, i: any) => (
                <div key={i} style={{ display: "flex", gap: "var(--s3)", marginBottom: i === analysis.basis.length - 1 ? 0 : "10px" }}>
                  <span style={{ color: "var(--info)" }} aria-hidden="true">&#10003;</span>
                  {b}
                </div>
              ))}
            </div>
            <div style={{ padding: "12px 16px", borderTop: "1px solid var(--line)" }}>
              <Note kind="info">
                Bedrock is analyzing the structured, cryptographically hashed evidence events from the ledger.
                It is not making assumptions based on unrecorded data.
              </Note>
            </div>
          </Panel>
        </div>

        <div>
          <Panel title="EVIDENCE REFERENCES">
            {analysis.refs.map((r: any, i: any) => (
              <div key={i} className="mono" style={{ fontSize: 11.5, padding: "5px 0", borderBottom: "1px solid var(--line)" }}>
                {r}
              </div>
            ))}
            <div style={{ marginTop: 12 }}>
              <button className="btn sm" onClick={() => go("evidence")}>Open evidence ledger</button>
            </div>
          </Panel>

          <Panel title="WHAT BEDROCK DOES NOT ASSERT">
            <div className="dim">
              {analysis.notAsserted.map((n: any, i: any) => (
                <div key={i} style={{ display: "flex", gap: "var(--s3)", marginBottom: i === analysis.notAsserted.length - 1 ? 0 : "10px" }}>
                  <span aria-hidden="true">&#10005;</span>
                  {n}
                </div>
              ))}
            </div>
          </Panel>
        </div>
      </div>
    </>
  );
}
