import React, { useState } from "react";
import PageHead from "../shared/PageHead.tsx";
import Panel from "../shared/Panel.tsx";
import Chip from "../shared/Chip.tsx";
import Note from "../shared/Note.tsx";
import SourceFlag from "../shared/SourceFlag.tsx";
import aegisApi from "../../data/aegisApi.ts";
import { SESSION } from "../../data/fixtures.js";

export default function Investigations({ events, analysis, analysisSource, setAnalysis, go }: any) {
  const deny = events.find((e: any) => e.decision === "DENY");
  const targetEvent = deny || events[events.length - 1];
  const [running, setRunning] = useState(false);

  const runInvestigation = async () => {
    if (!targetEvent || !setAnalysis) return;
    setRunning(true);
    try {
      const result = await aegisApi.investigate(targetEvent.id);
      setAnalysis(result);
    } finally {
      setRunning(false);
    }
  };

  return (
    <>
      <PageHead
        title="Investigations"
        desc="Grounded forensic synthesis from recorded evidence. Amazon Bedrock is invoked post-hoc on bounded ledger events and holds zero runtime authorization authority."
        actions={
          <>
            <SourceFlag source={analysisSource || "UNAVAILABLE"} />
            <button className="btn primary" onClick={runInvestigation} disabled={!targetEvent || running}>
              {running ? "Running investigation..." : "Run post-hoc investigation"}
            </button>
            <button className="btn" onClick={() => go("tests")}>Security tests</button>
          </>
        }
      />

      <Panel flush style={{ marginBottom: "var(--s5)" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "var(--s5)", padding: "var(--s4)", flexWrap: "wrap" }}>
          <div>
            <div className="mono dim" style={{ fontSize: 9.5, letterSpacing: ".12em" }}>TRIGGERING EVENT</div>
            <div className="mono" style={{ fontSize: 13, marginTop: 2 }}>{targetEvent ? targetEvent.id : "NO_EVENT_RECORDED"}</div>
          </div>
          <div>
            <div className="mono dim" style={{ fontSize: 9.5, letterSpacing: ".12em" }}>SESSION</div>
            <div className="mono" style={{ fontSize: 13, marginTop: 2 }}>{SESSION.id}</div>
          </div>
          <div>
            <div className="mono dim" style={{ fontSize: 9.5, letterSpacing: ".12em" }}>EVIDENCE LEDGER</div>
            <div style={{ marginTop: 2 }}>
              <span className="mono" style={{ fontSize: 13 }}>{events.length}</span>{" "}
              <span className="dim mono" style={{ fontSize: 11 }}>EVENTS</span>
            </div>
          </div>
          <div style={{ marginLeft: "auto" }}>
            <div className="mono dim" style={{ fontSize: 9.5, letterSpacing: ".12em", marginBottom: 5 }}>BEDROCK STATE</div>
            <Chip kind={(analysisSource || "UNAVAILABLE") === "LIVE_VERIFIED" ? "allow" : "info"}>
              {(analysisSource || "UNAVAILABLE").replace(/_/g, " ")}
            </Chip>
          </div>
        </div>
      </Panel>

      <div className="grid g3">
        <div style={{ gridColumn: "1 / -2" }}>
          <Panel title="WHAT HAPPENED" flush right={<span className="dim mono" style={{ fontSize: 10 }}>generated by {analysis.generatedBy}</span>}>
            <div style={{ padding: "var(--s4)", fontSize: 14, lineHeight: 1.6 }}>
              {analysis.whatHappened.map((p: any, i: any) => (
                <p key={i} style={{ marginTop: i === 0 ? 0 : "1em", marginBottom: 0 }}>{p}</p>
              ))}
            </div>
          </Panel>

          <Panel title="BASIS OF ANALYSIS" flush>
            <div style={{ padding: "var(--s4)" }}>
              {analysis.basis.map((b: any, i: any) => (
                <div key={i} style={{ display: "flex", gap: "var(--s3)", marginBottom: i === analysis.basis.length - 1 ? 0 : "10px" }}>
                  <span style={{ color: "var(--info)" }} aria-hidden="true">&#10003;</span>
                  {b}
                </div>
              ))}
            </div>
            <div style={{ padding: "12px 16px", borderTop: "1px solid var(--line)" }}>
              <Note kind="info">
                Bedrock is analyzing the structured, cryptographically hashed evidence events from the ledger.
                It is not making assumptions based on unrecorded data.
              </Note>
            </div>
          </Panel>
        </div>

        <div>
          <Panel flush style={{ marginBottom: "var(--s5)", border: "1px solid var(--info)", background: "linear-gradient(180deg, rgba(94,143,201,0.08) 0%, transparent 100%)" }}>
            <div style={{ padding: "var(--s4)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "var(--s3)", marginBottom: "var(--s4)" }}>
                <div style={{ width: 32, height: 32, borderRadius: "50%", background: "var(--info-bg)", border: "1.5px solid var(--info)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>&#128737;</div>
                <div>
                  <div className="mono" style={{ fontSize: 11, letterSpacing: "0.1em", color: "var(--info)" }}>NEGATIVE ASSERTIONS SHIELD</div>
                  <div style={{ fontSize: 14, fontWeight: 600, color: "var(--fg)" }}>ZERO RUNTIME GATING AUTHORITY</div>
                </div>
              </div>
              <div>
                {analysis.notAsserted.map((n: any, i: any) => (
                  <div key={i} style={{ display: "flex", gap: "var(--s3)", marginBottom: i === analysis.notAsserted.length - 1 ? 0 : "12px", alignItems: "flex-start", lineHeight: 1.5 }}>
                    <span style={{ color: "var(--deny)", flexShrink: 0, marginTop: 2 }} aria-hidden="true">&#10005;</span>
                    <span style={{ color: "var(--fg)", fontSize: 13 }}>{n}</span>
                  </div>
                ))}
              </div>
            </div>
            <div style={{ padding: "10px 16px", borderTop: "1px solid var(--info)", background: "rgba(94,143,201,0.06)", fontSize: 11, color: "var(--muted)" }}>
              Bedrock is a post-hoc forensic synthesis tool. It holds zero runtime authorization capability.
            </div>
          </Panel>

          <Panel title="EVIDENCE REFERENCES">
            {analysis.refs.map((r: any, i: any) => (
              <div key={i} className="mono" style={{ fontSize: 11.5, padding: "5px 0", borderBottom: "1px solid var(--line)" }}>
                {r}
              </div>
            ))}
            <div style={{ marginTop: 12 }}>
              <button className="btn sm" onClick={() => go("evidence")}>Open evidence ledger</button>
            </div>
          </Panel>
        </div>
      </div>
    </>
  );
}
